name: Sync Space
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: idlefingers/do-space-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: './opt/mayday-site'
        SPACE_NAME: "mayday-site-github"
        SPACE_REGION: "NYC1"
        SPACE_ACCESS_KEY_ID: ${{ secrets.SSHKEY }}
        SPACE_SECRET_ACCESS_KEY: "digitalocean"
